//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Расчёт_Себестоимости
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resources
    {
        public int IdResources { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public int IdType { get; set; }
    
        public virtual ResourcesType ResourcesType { get; set; }
    }
}
